apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      labels:
        app: project1
    spec:
        containers:
        - name: project1
          image: mbdocker001/project1:latest
          ports:
            - containerPort: 8084
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: project1
spec:
  selector:
    app: project1
  type: NodePort  
  ports:
  - name: http
    protocol: TCP
    port: 8084
    nodePort: 30020
 